In [2]:
import pandas as pd
import numpy as np

In [ ]:
input = [2,3,4,5]
weights=[0.1,0.2,0.3,0.4]
bias=2
output = (input [0]*weights[0]+
    input [1]*weights [1]+
    input [2]*weights[2]+input [3]*weights[3]+ bias)

output = max(0,output) #relu
print(output)

6.0


In [22]:
input = [2,3,4,5]
weights1=[0.1,0.2,0.3,0.4]
weights2=[0.2,0.3,0.4,0.5]
weights3=[0.3,0.4,0.5,0.6]
bias1=-5
bias2=6
bias3=2
output = [(input [0]*weights1[0]+input [1]*weights1[1]+input [2]*weights1[2]+input [3]*weights1[3]+ bias1),
          (input [0]*weights2[0]+input [1]*weights2[1]+input [2]*weights2[2]+ input [3]*weights2[3]+bias2),
          (input [0]*weights3[0]+input [1]*weights3[1]+input [2]*weights3[2]+ input [3]*weights3[3]+bias3)]
output=np.maximum(0,output)
print(output)

[ 0.  11.4  8.8]


In [21]:
input = np.array([2, 3, 4])

# 2. Combine weights into a single 2D matrix W (shape: 3 neurons x 3 inputs)
Weights = np.array([
    [0.1, 0.2, 0.3],  # weights1
    [0.2, 0.3, 0.4],  # weights2
    [0.3, 0.4, 0.5]   # weights3
])

# 3. Combine biases into a single 1D array b
bias = np.array([-5, 6, 2])

# 4. Compute output using dot product
output = np.dot(Weights, input) + bias
output=np.maximum(0,output)
print(output.tolist())

[0.0, 8.9, 5.800000000000001]


In [20]:
inputs = [2, 3, 4, 5]


weights = [
    [0.1, 0.2, 0.3],  # Neuron 1 weights
    [0.2, 0.3, 0.4],  # Neuron 2 weights
    [0.3, 0.4, 0.5]   # Neuron 3 weights
]

# 3. Combined bias vector (List)
bias = [-5, 6, 2]

# 4. Compute output using loops
output = []
for i in range(len(weights)):
    neuron_sum = 0
    for j in range(len(weights[i])):
        neuron_sum += inputs[j] * weights[i][j]
    
    # Add the bias for the current neuron and save the result
    output.append(neuron_sum + bias[i])
output=np.maximum(0,output)
print(output)

[0.  8.9 5.8]


In [19]:
inputs = [2, 3, 4, 5]

weights = [
    [0.1, 0.2, 0.3, 0.4],  
    [0.2, 0.3, 0.4, 0.5],  
    [0.3, 0.4, 0.5, 0.6]   
]

bias = [-5, 6, 2]


output = [
    (inputs[0]*weights[0][0] + inputs[1]*weights[0][1] + inputs[2]*weights[0][2] + inputs[3]*weights[0][3] + bias[0]),
    (inputs[0]*weights[1][0] + inputs[1]*weights[1][1] + inputs[2]*weights[1][2] + inputs[3]*weights[1][3] + bias[1]),
    (inputs[0]*weights[2][0] + inputs[1]*weights[2][1] + inputs[2]*weights[2][2] + inputs[3]*weights[2][3] + bias[2])
]
output=np.maximum(0,output)
print(output)

[ 0.  11.4  8.8]


In [25]:
input = [2,3,4,5]
weights=[0.1,0.2,0.3,0.4]
bias=2
output = np.dot(weights, input) + bias
output=np.maximum(0,output)
output = max(0,output) #relu
print(output)

6.0


In [29]:
inputs = [[0.3, 0.5, -0.3, 2],
          [0.6,-0.83,0.59,-0.6],
          [6,1,7,1]]

weights = [
    [0.1, 0.2, 0.3, 0.4],  
    [0.2, 0.3, 0.4, 0.5],  
    [0.3, 0.4, 0.5, 0.6]   
]
bias = [-5, 6, 2]
layer_output=np.dot(inputs,np.array(weights).T) + bias
print(layer_output)

[[-4.16   7.09   3.34 ]
 [-5.169  5.807  1.783]
 [-1.7   10.8    8.3  ]]


In [30]:
inputs = [[0.3, 0.5, -0.3, 2],
          [0.6, -0.83, 0.59, -0.6],
          [6, 1, 7, 1]]

weights = [
     [0.1, 0.2, 0.3, 0.4],
     [0.2, 0.3, 0.4, 0.5],
     [0.3, 0.4, 0.5, 0.6]
]

bias = [-5, 6, 2]

# Compute linear combination layer outputs
layer_output = np.dot(inputs, np.array(weights).T) + bias

# Define custom sigmoid activation function 
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Apply activation to the matrix
activated_output = sigmoid(layer_output)

print(activated_output)

[[0.01536771 0.9991673  0.96577584]
 [0.00565806 0.99700258 0.85606691]
 [0.15446527 0.9999796  0.99975154]]


In [32]:

# 1. Inputs: 3 students, 4 features each
# Features: [Attendance, Midterm, Assignments, Final Exam]
inputs = np.array([
    [0.95, 0.85, 0.90, 0.88],  # Student 1
    [0.40, 0.50, 0.45, 0.30],  # Student 2
    [0.75, 0.65, 0.70, 0.60]   # Student 3
])

# 2. Weights: 1 row representing 1 output neuron (Pass/Fail)
weights = np.array([
    [2.0, 1.5, 1.5, 4.0]
])

bias = np.array([-4.5])

output = np.dot(inputs, weights.T) + bias

# 5. Activation Function: Sigmoid converts scores to probabilities between 0 and 1
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

probabilities = sigmoid(output)

# 6. Classification: 1 if Probability >= 0.5 (Pass), else 0 (Fail)
predictions = (probabilities >= 0.5).astype(int)

# Display Results
for i, (prob, pred) in enumerate(zip(probabilities.flatten(), predictions.flatten())):
    status = "Pass" if pred == 1 else "Fail"
    print(f"Student {i+1}: {status}")


Student 1: Pass
Student 2: Fail
Student 3: Pass


In [9]:

inputs = [[0.3, 0.5, -0.3, 2],
          [0.6,-0.83,0.59,-0.6],
          [6,1,7,1]]

weights = [
    [0.1, 0.2, 0.3, 0.4],  
    [0.2, 0.3, 0.4, 0.5],  
    [0.3, 0.4, 0.5, 0.6]   
]
bias = [-5, 6, 2]
weights2 = [
    [0.1, 0.2, 0.3],  
    [0.2, 0.3, 0.4],  
    [0.3, 0.4, 0.5]   
]
bias2 = [-5, 3, 2]
layer_output=np.dot(inputs,np.array(weights).T) + bias
layer_output=np.maximum(0,layer_output)
layer_output2=np.dot(layer_output,np.array(weights2).T) + bias2
layer_output2=np.maximum(0,layer_output2)
print(layer_output2)

[[ 0.      6.463   6.506 ]
 [ 0.      5.4553  5.2143]
 [ 0.      9.56   10.47  ]]
